language: generic 
sudo: required
services:
  - docker


before_install:
  # This tag will only being used in the travis instance 
  - docekr build -t dogun098/docker-react -f Dockerfile.dev .

# supposed to contain all command to excute
script:
  - docker run -e CI=true dogun098/docker-react npm run test